### ISSUE TITLE
need to handle array (object) subdata

### ISSUE THREAD

**Issue by mydesign** [adamwulf/json-to-mysql#10]
How to receive subdata Events?

{ "CommandStatus": "0", "Events": [ { "ActivityId": "1" },{ "ActivityId": "2" },...,{ "ActivityId": "867" } ], "EventsCount": "867" }

**Comment by adamwulf** [comment]
right now it works w/ single objects, so to save those 867 events you'll need to ->save() each one

**Comment by danipolo** [comment]
@adamwulf im so interested in that.  Im getting that error when i try to import a json with subdata.

Can you explain little bit more how to solve that?

Thanks!

**Comment by adamwulf** [comment]
I just mean you'd have to do something like (in pseudo code):
```
for($commandStatus->events as $event){
    $table->save($event);
}
```

instead of 
```
$table->save($commandStatus)
```
