### ISSUE TITLE
Your software doesn't work

### ISSUE THREAD

**Issue by tunage** [adamwulf/json-to-mysql#12]
I am getting a NULL value from the class, but all files are found.
The return JSON object is fully populated with data.

<!DOCTYPE html>
<html>
<head>

</head>

<body>
<title>Analytics</title>
<h2>  Dump by ID </h2>
<?php
session_start();
include("config.php");
include("include.classloader.php");

if (isset($_POST['objectID'])) {
}
$_POST['submit'] = "BurciagaBlends";

if(isset($_POST['submit'])){
        $objectID = $_POST['objectID'];
        if($objectID !=''){
                //BurciagaBlends
                $url = "https://api.instagram.com/v1/tags/".$_POST['objectID']."/media/recent?access_token=1640112569.a42c0ba.c2cd7ea1804d4cc094dab967a59962f4";
                //$url = "https://api.instagram.com/v1/media/".$_POST['objectID']."/likes?access_token=1640112569.a42c0ba.c2cd7ea1804d4cc094dab967a59962f4";
                $ch = curl_init();

                curl_setopt($ch,CURLOPT_URL,$url);
                curl_setopt($ch,CURLOPT_RETURNTRANSFER,true);
                curl_setopt($ch,CURLOPT_HEADER, false);
                curl_setopt($ch, CURLOPT_HTTPHEADER, array('Accept: application/x-www-form-urlencoded; charset=UTF-8'));

                $output = curl_exec($ch);
                curl_close($ch);
                $arr = json_decode($output,true);
                var_dump($output);

        }
}

$classLoader->addToClasspath(ROOT);

$mysql = new MySQLConn(DATABASE_HOST, DATABASE_NAME, DATABASE_USER, DATABASE_PASS);

$db = new JSONtoMYSQL($mysql);

// create some json
$obj = json_decode($output);

// save it to a table
$db->save($obj, "brandnewtable");

?>

<div class="gradientBoxesWithOuterShadows">
<p>Enter the Object ID you would like for me to retrieve 'hearts' for.</p>
</br>

<form action="" id="#form" method="post" name="#form">
<label>Object ID :</label>
<input id="objectID" name="objectID" type='text'>
<input id='btn' name="submit" type='submit' value='Submit'>

</div>
</body>

</html>

**Comment by tunage** [comment]
the most I can find, from a var_dump($db); is


classpath = array(); } public function addToClasspath($dir){ if(is_dir($dir)){ $this->classpath[] = $dir; }else{ throw new Exception("cannot find directory: $dir"); } } public function load($classname){ $ok = false; for($i=0;$iclasspath);$i++){ $path = $this->classpath[$i]; /* echo "load recur \"" . $path . "\";//
\n"; */ $ok = $ok || $this->load_recursive($path, $classname); } return $ok; } protected function load_recursive($classpath, $classname){ $theList = array(); $ret = false; if ($handle = opendir($classpath)) { while (false != ($file = readdir($handle))) { if ($file != "." && $file != "..") { if(is_dir($classpath . $file)){ $ret = $ret || $this->load_recursive($classpath . $file . "/", $classname); }else{ if($file == "class.$classname.php"){ include_once $classpath . $file; $ret = true; /* echo "include_once \"" . $classpath . $file . "\";//
\n"; */ }else if($file == "class.Boolean.$classname.php"){ include_once $classpath . $file; $ret = true; /* echo "include_once \"" . $classpath . $file . "\";//
\n"; */ }else if($file == "interface.$classname.php"){ include_once $classpath . $file; $ret = true; /* echo "include_once \"" . $classpath . $file . "\";//
\n"; */ } } } } closedir($handle); unset($handle); } return $ret; } public function loadTestFiles(GroupTest $g){ foreach($this->classpath as $c){ $this->loadTestFilesHelper($g, $c); } } protected function loadTestFilesHelper(GroupTest $g, $classpath){ $theList = array(); if ($handle = opendir($classpath)) { while (false != ($file = readdir($handle))) { if ($file != "." && $file != "..") { if(is_dir($classpath . $file)){ $this->loadTestFilesHelper($g, $classpath . $file . "/"); }else{ if(strpos($file, "test.class.") === 0 && strpos($file, ".php") == strlen($file)-4){ $g->addTestFile($classpath . $file); } } } } closedir($handle); unset($handle); } } } class ClassLoaderToString extends ClassLoader{ public function __construct(){ parent::__construct(); } protected function load_recursive($classpath, $classname){ $theList = array(); $ret = false; if ($handle = opendir($classpath)) { while (false != ($file = readdir($handle))) { if ($file != "." && $file != "..") { if(is_dir($classpath . $file)){ $this->load_recursive($classpath . $file . "/", $classname); }else{ if($file == "class.$classname.php"){ include_once $classpath . $file; $this->printClass($classpath, $file); $ret = true; }else if($file == "class.Boolean.$classname.php"){ include_once $classpath . $file; $this->printClass($classpath, $file); $ret = true; }else if($file == "interface.$classname.php"){ include_once $classpath . $file; $this->printClass($classpath, $file); $ret = true; } } } } closedir($handle); unset($handle); } return $ret; } protected function printClass($classpath, $file){ if(strpos($classpath, ROOT) === 0){ $classpath = substr($classpath, strlen(ROOT)); echo "include_once(ROOT . \"" . $classpath . $file . "\");\n"; }else{ echo "include_once(\"" . $classpath . $file . "\");\n"; } } } function milestone_autoload($classname){ global $classLoader; //	global $control; //	$str = "classname: "; //	$str .= $classname; //	$str .= "\n"; //	if(is_object($control) && !is_int(stripos($classname, "mysql"))){ //	$control->getModel()->getLogger()->log($control->getModel(), ALogger::$HIGH, $str); //	} try{ $ok = $classLoader->load($classname); //	$str .= ":" . $ok; // if(is_object($control) && !is_int(stripos($classname, "mysql"))){ //	$control->getModel()->getLogger()->log($control->getModel(), ALogger::$HIGH, $str); //	} }catch(Exception $e){ $model->getLogger()->log($model, ALogger::$HIGH, print_r($e, true)); } } spl_autoload_register('milestone_autoload'); $classLoader = new ClassLoader(); ?>
Notice: Undefined variable: classLoader in /usr/local/www/apache24/data/json-to-mysql/insertHash.php on line 68

Fatal error: Call to a member function addToClasspath() on null in /usr/local/www/apache24/data/json-to-mysql/insertHash.php on line 68




I don't know why the value is NULL. the return data is fully populated and all files are found.

**Comment by adamwulf** [comment]
it looks like include.classloader.php isn't included in your script. Include that file and retry, does that fix it?

**Comment by adamwulf** [comment]
closing since no response
