### ISSUE TITLE
"search, update, index, and validate tables with JSON" - How?

### ISSUE THREAD

**Issue by theitd** [adamwulf/json-to-mysql#16]
The example given works beautifully - however, when adding the same JSON data, the $db->save(...) method creates a duplicate in the resulting table.  Is it possible to check for the row first and avoid duplicated entries - ie.  if (!$db->find($json_object,"table") ...?

If someone could "flesh out" the example to include any other functions (search, update...), it would be hugely appreciated.

**Comment by adamwulf** [comment]
I need to update the README, but you can use the find() method on the table objects. The find() method takes two arguments. the first is the list of fields to match along with their respective values. the second is optional operator to use for each field. For example, to search an imaginary users table:

```
$userstable = $db->table("users");
$userstable->find(array("last_update" => date("Y-m-d", time()-24*60*60),
					    "username" => "someuser"),
					    array("last_update" => "<="));
```

If an operator isn't provided, then it'll default to LIKE for text columns and = for everything else. The provided values can be an array, and in that case it'll use `field IN (values array here)` for the search

**Comment by theitd** [comment]
Thanks very much for the explanation.  It makes much better sense.
I realised I was entering duplicates because I hadn't specified a unique ID for the JSON being inserted.  The find & update worked automatically if the ID column was included.

I'm using the project to reduce times on a query which, up until now, used common_schema2.2 to extract the JSON.  The difference is staggering (~75s down to ~18s).  So thanks again!

**Comment by adamwulf** [comment]
awesome glad to hear it!
