### ISSUE TITLE
example.php does not work

### ISSUE THREAD

**Issue by sbash** [adamwulf/json-to-mysql#18]
when I run:
$ php example.php

I get:

PHP Notice:  Undefined variable: classLoader in /home/sbash/json-to-mysql/example.php on line 10
PHP Fatal error:  Call to a member function addToClasspath() on null in /home/sbash/json-to-mysql/example.php on line 10

I only edited the file to add <?php as short tags do not work in my environment.  I get this on php 7.x and 5.6...  

I have tested this on a clean 'git clone ...'  just making the short tag modification above to no avail...

**Comment by franperr** [comment]
I had the same problem, it's because almost all the php files start with <? instead of <?php . So you have to change it in every php file (including libraries).

**Comment by adamwulf** [comment]
I just pushed up a commit that changes <? to <?php, see if that does the trick. The example.php is working fine for me.

**Comment by sbash** [comment]
Yes, good call.  Instead of re-downloading your update, I enabled short tags and it works now.

Thanks!
