### ISSUE TITLE
Example typo and bug in line 208

### ISSUE THREAD

**Issue by vermeerpaul** [adamwulf/json-to-mysql#22]
1) bug in code
Line 208 in ExistingMYSQLTable.php should use variable `$val` instead of `$value`. You do not iterate with the correct element used.

2) Your example in README.md has a typo
`$obj = $db->table("brandnewtable")->find(["id" => [4, 5, 6 7]]);` should be
`$obj = $db->table("brandnewtable")->find(["id" => [4, 5, 6, 7]]);` note the missing comma.

**Comment by adamwulf** [comment]
fixed in 54dd8cb6

Thanks!
